lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^(\d+)/add_item$', views.add_item, name='add_item'),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views  #1
from lists import urls as list_urls  #2

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
    # url(r'^admin/', include(admin.site.urls)),
]

lists/models.py
from django.db import models

class List(models.Model):
    pass
    
class Item(models.Model):
    angka = models.IntegerField(default=0)
    tebakan = models.IntegerField(default=0)
    status = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

lists/views.py
from django.shortcuts import redirect, render
from lists.models import Item, List
import random

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    comment = insert_comment(list_)
    return render(request, 'list.html', {'list':list_, 'comment':comment})

def home_page(request):
    return render(request, 'home.html')

def new_list(request):
    list_ = List.objects.create()
    
    angkaRandom = random.randint(1,30)
    angkaTebakan = int(request.POST['item_text'])    
    
    item=Item()
    item.angka = angkaRandom
    item.tebakan = angkaTebakan
    item.status = lihatStatus(angkaRandom, angkaTebakan)
    item.list = list_
    item.save()
    
    return redirect('/lists/%d/' % (list_.id,))
    
def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    angkaRandom = random.randint(1,30)
    angkaTebakan = int(request.POST['item_text'])    
    
    item=Item()
    item.angka = angkaRandom
    item.tebakan = angkaTebakan
    item.status = lihatStatus(angkaRandom, angkaTebakan)
    item.list = list_
    item.save()

    return redirect('/lists/%d/' % (list_.id,))

def lihatStatus(angka, tebakan):
    if tebakan<angka+2 and tebakan>angka-2:
    	return 'Kamu menang!!'
    else:
        return 'Kamu kalah...'

def insert_comment(list_periksa):
    list_temp = Item.objects.filter(list=list_periksa).reverse()
    counter = 0
    comment = ''

    if len(list_temp)<3:
        return comment

    for i in range(3):
        item=list_temp[i]
        if item.status == 'Kamu menang!!':
            counter = counter+1

    if counter == 3:
        comment = 'Ulala!!'

    if len(list_temp)<5:
        return comment

    counter = 0

    for i in range(5):
        item = list_temp[i]
        if item.status == 'Kamu menang!!':
            counter = counter+1

    if counter == 5:
        comment = 'Ulalala'

    if len(list_temp)<10:
        return comment

    counter = 0

    for i in range(10):
        item = list_temp[i]
        if item.status == 'Kamu menang!!':
            counter = counter+1

    if counter == 10:
        comment = 'Uulala'

    return comment

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Simulasi UAS</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
</head>

<body>
<div class="container">

    <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <div class="text-center">
                <h1>{% block header_text %}{% endblock %}</h1>
                {{ comment }}
                <form method="POST" action="{% block form_action %}{% endblock %}">
                    <input name="item_text" id="id_new_item"
                           class="form-control input-lg"
                           placeholder="Enter an integer 1-30"
                    />
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block table %}
            {% endblock %}
        </div>
    </div>

</div>
</body>
</html>

lists/templates/home.html
<html>
    <head>
        <title>Simulasi UAS</title>
    </head>
    <body>
        {% extends 'base.html' %}
        <h1>{% block header_text %}Game Tebak Angka{% endblock %}</h1>
        <form method="POST" action="{% block form_action %}/lists/new{% endblock %}">
            <input name="item_text" id="id_new_item"
            placeholder="Enter an integer 1-30"
            />
            {% csrf_token %}
        </form>
    </body>
</html>

lists/templates/list.html
<html>
    <head>
        <title>Simulasi UAs</title>
    </head>
    <body>
         {% extends 'base.html' %}
         <h1>{% block header_text %}Game Tebak Angka{% endblock %}</h1>
         <form method="POST" action="{% block form_action %}/lists/{{ list.id }}/add_item{% endblock %}">
         <input name="item_text" id="id_new_item" placeholder="enter a to-do item" />
         
         <span>{% block comment_text %}{{ comment }}{% endblock %}</span>
    </body>
</html>


{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>Angka : {{ item.angka }}, Tebakan :{{ item.tebakan }}, {{ item.status }}</td></tr>
        {% endfor %}
    </table>
{% endblock %}